#!/usr/bin/env python3
"""Lexicon pipeline step: generate noun declension paradigms ("hold groups")
from the lemmas of an engine lexicon.

The hold-popup shows the forms of a lemma when the user long-presses a
suggestion. Returning every form in a pile is a "morphological salad"; the
useful shape is a case-ordered grid, split by number. This tool emits that
grid so the runtime never has to inflect on device.

It reads the lemma column (2nd) of a lexicon TSV, re-parses each distinct
lemma, and for every noun lemma generates the six cases in each available
number via morphological *generation* (`inflect`). Nouns carry lexical
gender, so {case, number} fully determines the form — no gender dimension
is needed (unlike adjectives/participles, deliberately out of scope here).
Singularia/pluralia tantum naturally yield only the number that exists.

Output (sorted, one row per lemma+number, pipe-joined in fixed case order
nomn|gent|datv|accs|ablt|loct; empty slot = no such form):

    lemma<TAB>number<TAB>nomn|gent|datv|accs|ablt|loct
    работа	sing	работа|работы|работе|работу|работой|работе
    работа	plur	работы|работ|работам|работы|работами|работах

Offline tooling only — never runs on device. Idempotent: same input ->
byte-identical output.

    pip install mawo-pymorphy3        # bundled OpenCorpora 2025 DAWG dicts
    python3 paradigms.py data/lexicons/ru-50k.tsv data/lexicons/ru-hold-groups.tsv
"""

import os
import sys
import tempfile

# Fixed grammatical-case order. Matches abbrev_core::morph case naming so the
# columns line up with the engine's morphology layer.
CASES = ["nomn", "gent", "datv", "accs", "ablt", "loct"]
NUMBERS = ["sing", "plur"]


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: paradigms.py <lexicon.tsv> <out-hold-groups.tsv>", file=sys.stderr)
        return 1
    src, out = sys.argv[1], sys.argv[2]
    # Validate the input before the heavy import: a bad path should be
    # reported as such, not as a missing dependency.
    try:
        probe = open(src, encoding="utf-8")
    except OSError as e:
        print(f"cannot read {src}: {e}", file=sys.stderr)
        return 1
    with probe:
        lemmas = set()
        for line_no, raw in enumerate(probe, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            # Enforce the engine's lexicon contract (see lexicon.rs): exactly
            # form<TAB>lemma<TAB>freq, with an optional 4th grammeme column.
            # Anything else is a drifted/broken artifact — fail fast like the
            # engine does, rather than silently building paradigms from it.
            if len(parts) not in (3, 4) or not parts[1]:
                print(
                    f"{src}:{line_no}: expected form<TAB>lemma<TAB>freq[<TAB>tags]",
                    file=sys.stderr,
                )
                return 1
            lemmas.add(parts[1])

    # Lazy import: usage and argument errors must not require the dependency.
    try:
        import mawo_pymorphy3

        morph = mawo_pymorphy3.create_analyzer()
    except ModuleNotFoundError:
        print(
            "mawo-pymorphy3 is not installed; run: pip install mawo-pymorphy3",
            file=sys.stderr,
        )
        return 1

    rows = []
    skipped_non_noun = 0
    for lemma in lemmas:
        # Pick the noun parse whose normal form is the lemma itself, so we
        # inflect the intended lexeme (e.g. "стали" -> the verb "стать" is
        # not what a lemma-keyed paradigm wants).
        noun = next(
            (
                p
                for p in morph.parse(lemma)
                if p.tag.POS == "NOUN" and p.normal_form == lemma
            ),
            None,
        )
        if noun is None:
            skipped_non_noun += 1
            continue
        for number in NUMBERS:
            forms = []
            for case in CASES:
                inflected = noun.inflect({case, number})
                forms.append(inflected.word if inflected else "")
            # Drop a number the lexeme does not have (singularia/pluralia
            # tantum) instead of emitting an all-empty row.
            if any(forms):
                rows.append(f"{lemma}\t{number}\t" + "|".join(forms))

    rows.sort()
    header = (
        "# Russian noun declension paradigms (hold-popup groups).\n"
        "# Generated by scripts/paradigms.py from the lexicon's lemmas via\n"
        "# mawo-pymorphy3 (OpenCorpora 2025 dicts, CC BY-SA 3.0).\n"
        "# lemma<TAB>number<TAB>nomn|gent|datv|accs|ablt|loct  (empty = no form)\n"
    )
    # Atomic replace: a crash mid-write must not corrupt the artifact.
    out_dir = os.path.dirname(out) or "."
    try:
        fd, tmp = tempfile.mkstemp(dir=out_dir, suffix=".tmp")
    except OSError as e:
        print(f"cannot create temp file in {out_dir}: {e}", file=sys.stderr)
        return 1
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(header)
            f.write("\n".join(rows))
            f.write("\n")
        os.replace(tmp, out)
    except BaseException:
        os.unlink(tmp)
        raise
    print(
        f"wrote {out}: {len(rows)} paradigm rows "
        f"({len(lemmas)} lemmas, {skipped_non_noun} non-noun skipped)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
