//! Abbreviation generator: turns a frequency lexicon into a large
//! benchmark by *corrupting words the way people abbreviate them*.
//!
//! Encoded typology (each rule mirrors a cost in the engine's edit model):
//! 1. the first letter always survives;
//! 2. internal vowels drop (the core abbreviation move);
//! 3. the ending is often kept intact — it encodes the inflection;
//! 4. `ь`/`ъ` drop, double letters collapse;
//! 5. right truncation (plain prefix) as a separate mode;
//! 6. conventional slang is *lexicon* material, not a rule — not generated;
//! 7. a typo layer on top: adjacent-key substitution or transposition.
//!
//! Deterministic for a given `--seed`, so benchmarks are reproducible
//! without committing megabytes of generated cases.

use std::process::ExitCode;

use abbrev_core::Lexicon;
use abbrev_core::alphabet::{is_sign, is_vowel, keyboard_adjacent, normalize};

const RUSSIAN_LETTERS: &str = "абвгдежзийклмнопрстуфхцчшщъыьэюя";

/// xorshift64 — deterministic, dependency-free.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed.max(1))
    }

    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn f64(&mut self) -> f64 {
        (self.next() >> 11) as f64 / (1u64 << 53) as f64
    }

    fn chance(&mut self, p: f64) -> bool {
        self.f64() < p
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

pub fn cmd_gen(args: Vec<&str>) -> ExitCode {
    let mut lexicon_path: Option<String> = None;
    let mut output: Option<String> = None;
    let mut count = 10_000usize;
    let mut seed = 42u64;
    let mut it = args.into_iter();
    while let Some(arg) = it.next() {
        match arg {
            "--lexicon" => lexicon_path = it.next().map(String::from),
            "-o" | "--output" => output = it.next().map(String::from),
            "--count" => match it.next().and_then(|v| v.parse().ok()) {
                Some(v) => count = v,
                None => return fail("--count needs a number"),
            },
            "--seed" => match it.next().and_then(|v| v.parse().ok()) {
                Some(v) => seed = v,
                None => return fail("--seed needs a number"),
            },
            other => return fail(&format!("gen: unknown argument {other}")),
        }
    }
    let Some(lexicon_path) = lexicon_path else {
        return fail("gen needs --lexicon <path> (a real frequency lexicon)");
    };
    let tsv = match std::fs::read_to_string(&lexicon_path) {
        Ok(t) => t,
        Err(e) => return fail(&format!("cannot read {lexicon_path}: {e}")),
    };
    let lexicon = match Lexicon::from_tsv_str(&tsv) {
        Ok(l) => l,
        Err(e) => return fail(&e.to_string()),
    };

    // All normalized forms: a truncation that *is* another dictionary word
    // makes the expected answer unreachable without context — skip those.
    let all_forms: std::collections::HashSet<String> =
        lexicon.iter().map(|(_, e)| normalize(&e.form)).collect();

    // Pool: words long enough to be worth abbreviating, with vowels to drop.
    let pool: Vec<(String, f32)> = lexicon
        .iter()
        .map(|(_, e)| (normalize(&e.form), e.freq))
        .filter(|(form, _)| {
            form.chars().count() >= 5 && form.chars().filter(|&c| is_vowel(c)).count() >= 2
        })
        .collect();
    if pool.is_empty() {
        return fail("lexicon has no abbreviatable words (len >= 5, >= 2 vowels)");
    }

    // Frequency-weighted sampling: people abbreviate the words they use.
    let cumulative: Vec<f64> = pool
        .iter()
        .scan(0.0f64, |acc, (_, freq)| {
            *acc += f64::from(freq.max(0.0)) + 1.0;
            Some(*acc)
        })
        .collect();
    let total = *cumulative.last().expect("non-empty pool");

    let mut rng = Rng::new(seed);
    let mut out = String::new();
    out.push_str(&format!(
        "# generated by `abbrev gen --lexicon {lexicon_path} --count {count} --seed {seed}`\n\
         # input<TAB>expected<TAB>tag\n"
    ));
    let mut produced = 0usize;
    let mut attempts = 0usize;
    while produced < count && attempts < count * 20 {
        attempts += 1;
        let target = rng.f64() * total;
        let idx = cumulative.partition_point(|&c| c < target);
        let word = &pool[idx.min(pool.len() - 1)].0;
        let Some((input, tag)) = corrupt(word, &mut rng) else {
            continue;
        };
        if tag == "truncate" && all_forms.contains(&input) {
            continue;
        }
        out.push_str(&format!("{input}\t{word}\t{tag}\n"));
        produced += 1;
    }

    let result = match output {
        Some(path) => std::fs::write(&path, out)
            .map_err(|e| format!("cannot write {path}: {e}"))
            .map(|()| eprintln!("written {produced} cases to {path}")),
        None => {
            print!("{out}");
            Ok(())
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => fail(&e),
    }
}

/// Applies the abbreviation typology to one word. Returns the corrupted
/// input and a tag for per-rule benchmark breakdown, or `None` when the
/// corruption degenerates (too short / unchanged).
fn corrupt(word: &str, rng: &mut Rng) -> Option<(String, &'static str)> {
    let chars: Vec<char> = word.chars().collect();
    let mode = rng.f64();
    if mode < 0.15 {
        // Rule 5: right truncation — a plain prefix.
        let min = 4.min(chars.len() - 1);
        let len = min + rng.below(chars.len() - min);
        if len >= chars.len() {
            return None;
        }
        return Some((chars[..len].iter().collect(), "truncate"));
    }

    // Rules 1–4: skeleton-style corruption.
    // Rule 3: with p=0.6 the ending (last 2–3 chars) is protected verbatim.
    let keep_ending = rng.chance(0.6);
    let protected_tail = if keep_ending { 2 + rng.below(2) } else { 0 };
    let tail_start = chars.len().saturating_sub(protected_tail).max(1);

    let mut result: Vec<char> = Vec::with_capacity(chars.len());
    result.push(chars[0]); // rule 1: first letter survives
    for i in 1..chars.len() {
        let c = chars[i];
        if i >= tail_start {
            result.push(c);
            continue;
        }
        if is_vowel(c) && rng.chance(0.75) {
            continue; // rule 2: drop internal vowel
        }
        if is_sign(c) && rng.chance(0.8) {
            continue; // rule 4: drop ь/ъ
        }
        if chars[i - 1] == c && rng.chance(0.7) {
            continue; // rule 4: collapse double letters
        }
        result.push(c);
    }
    if result.len() < 3 || result.len() == chars.len() {
        return None;
    }

    // Rule 7: typo layer on top of the skeleton (15% of skeleton cases).
    if rng.chance(0.15) && result.len() >= 4 {
        let pos = 1 + rng.below(result.len() - 2);
        if rng.chance(0.5) {
            result.swap(pos, pos + 1); // transposition
        } else if let Some(neighbor) = random_neighbor(result[pos], rng) {
            result[pos] = neighbor; // adjacent-key substitution
        }
        let input: String = result.iter().collect();
        if input == word {
            return None;
        }
        return Some((input, "typo"));
    }

    let tag = if keep_ending { "ending" } else { "skeleton" };
    Some((result.iter().collect(), tag))
}

fn random_neighbor(c: char, rng: &mut Rng) -> Option<char> {
    let neighbors: Vec<char> = RUSSIAN_LETTERS
        .chars()
        .filter(|&other| keyboard_adjacent(c, other))
        .collect();
    if neighbors.is_empty() {
        None
    } else {
        Some(neighbors[rng.below(neighbors.len())])
    }
}

fn fail(message: &str) -> ExitCode {
    eprintln!("error: {message}");
    ExitCode::FAILURE
}
